version: '3.7'

services:
    cosignerpool:
        container_name: cosignerpool
        build:
            context: ../src
            dockerfile: $PWD/Cosignerpool/Dockerfile
        expose:
            - 50051
        networks:
            - cosignerpool
    memcached:
        container_name: memcached
        image: memcached:latest
        networks:
            - cosignerpool

networks:
        cosignerpool:
