version: '3.7'

services:
    cosignerpool:
        container_name: cosignerpool
        build:
            context: ../src
            dockerfile: $PWD/Cosignerpool/Dockerfile
        volumes:
            - "/db_cosigner:/db_cosigner"
        expose:
            - 50051
        networks:
            - cosignerpool

networks:
        cosignerpool:
